### ISSUE TITLE
Variables in quotes should be highlighted to be more visible

### ISSUE THREAD

**Issue by sprzenus** [chocoford/leaf-extension#1]
Currently, functions and variables used in a string are not visible.

![Screen Shot 2020-08-05 at 08 13 07](https://user-images.githubusercontent.com/28487528/89378138-7fef2f00-d6f3-11ea-853c-be041cf5c64f.png)

**Comment by chocoford** [comment]
now it has been fixed.
![](https://raw.githubusercontent.com/chocoford/leaf-extension/master/Public/CHANGELOG/0.0.6-1.png)
